server:
  port: 8080  

spring:
  datasource:
    url: jdbc:tc:postgresql:15:///testdb  #  Testcontainers PostgreSQL kullan
    driver-class-name: org.postgresql.Driver
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  #  PostgreSQL'e uygun dialect
    hibernate:
      ddl-auto: update  #  Tabloları silmemesi için "update" kullan (veya "none")
    show-sql: true  #  SQL sorgularını logda görmek için
  sql:
    init:
      mode: always  #  schema.sql ve data.sql her zaman çalıştırılsın
      platform: postgres  #  PostgreSQL kullanıldığını belirt

grpc:
  server:
    port: 9090  # Eğer gRPC kullanıyorsan, HTTP ile çakışmaması için farklı port seçmelisin
