CREATE TABLE LEAGUES (
    LEAGUE_ID SERIAL PRIMARY KEY,
    LEAGUE_NAME VARCHAR(255) NOT NULL UNIQUE,
    COUNTRY VARCHAR(255) NOT NULL
);

CREATE TABLE TEAMS (
    TEAM_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    LEAGUE_ID INT NOT NULL,
    FOREIGN KEY (LEAGUE_ID) REFERENCES LEAGUES(LEAGUE_ID) ON DELETE CASCADE
);

CREATE TABLE MATCHES (
    MATCH_ID SERIAL PRIMARY KEY,
    MATCH_DATE VARCHAR NOT NULL,
    HOME_TEAM_SCORE INT DEFAULT 0,
    AWAY_TEAM_SCORE INT DEFAULT 0,
    LEAGUE_ID INT NOT NULL,
    HOME_TEAM_ID INT NOT NULL,
    AWAY_TEAM_ID INT NOT NULL,
    FOREIGN KEY (LEAGUE_ID) REFERENCES LEAGUES(LEAGUE_ID) ON DELETE CASCADE,
    FOREIGN KEY (HOME_TEAM_ID) REFERENCES TEAMS(TEAM_ID) ON DELETE CASCADE,
    FOREIGN KEY (AWAY_TEAM_ID) REFERENCES TEAMS(TEAM_ID) ON DELETE CASCADE
);

CREATE TABLE MATCH_STATS (
    MATCH_STATS_ID SERIAL PRIMARY KEY,
    MATCH_ID INT NOT NULL,
    TEAM_ID INT NOT NULL,
    GOALS INT DEFAULT 0,
    YELLOW_CARDS INT DEFAULT 0,
    RED_CARDS INT DEFAULT 0,
    SHOTS INT DEFAULT 0,
    SHOTS_ON_TARGET INT DEFAULT 0,
    POSSESSION INT DEFAULT 0,
    FOULS_COMMITTED INT DEFAULT 0,
    FOREIGN KEY (MATCH_ID) REFERENCES MATCHES(MATCH_ID) ON DELETE CASCADE,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(TEAM_ID) ON DELETE CASCADE
);


CREATE TABLE TEAM_STATS (
    TEAM_STATS_ID SERIAL PRIMARY KEY,
    TEAM_ID INT NOT NULL,
    LEAGUE_ID INT NOT NULL,
    MATCHES_PLAYED INT DEFAULT 0,
    WINS INT DEFAULT 0,
    DRAWS INT DEFAULT 0,
    LOSSES INT DEFAULT 0,
    GOALS_SCORED INT DEFAULT 0,
    GOALS_CONCEDED INT DEFAULT 0,
    POINTS INT DEFAULT 0,
    GOAL_DIFFERENCE INT DEFAULT 0,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAMS(TEAM_ID) ON DELETE CASCADE,
    FOREIGN KEY (LEAGUE_ID) REFERENCES LEAGUES(LEAGUE_ID) ON DELETE CASCADE
);
