CREATE TABLE LEAGUE (
    LEAGUE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    LEAGUE_NAME VARCHAR(255) NOT NULL UNIQUE,
    COUNTRY VARCHAR(255) NOT NULL
);

CREATE TABLE TEAM (
    TEAM_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    LEAGUE_ID BIGINT NOT NULL,
    FOREIGN KEY (LEAGUE_ID) REFERENCES LEAGUE(LEAGUE_ID) ON DELETE CASCADE
);

CREATE TABLE MATCHES (
    MATCH_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    MATCH_DATE DATE NOT NULL,
    HOME_TEAM_SCORE INT DEFAULT 0,
    AWAY_TEAM_SCORE INT DEFAULT 0,
    LEAGUE_ID BIGINT NOT NULL,
    HOME_TEAM_ID BIGINT NOT NULL,
    AWAY_TEAM_ID BIGINT NOT NULL,
    FOREIGN KEY (LEAGUE_ID) REFERENCES LEAGUE(LEAGUE_ID) ON DELETE CASCADE,
    FOREIGN KEY (HOME_TEAM_ID) REFERENCES TEAM(TEAM_ID) ON DELETE CASCADE,
    FOREIGN KEY (AWAY_TEAM_ID) REFERENCES TEAM(TEAM_ID) ON DELETE CASCADE
);

CREATE TABLE MATCH_STATS (
    MATCH_STAT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    MATCH_ID BIGINT NOT NULL,
    TEAM_ID BIGINT NOT NULL,
    GOALS INT DEFAULT 0,
    YELLOW_CARD INT DEFAULT 0,
    RED_CARD INT DEFAULT 0,
    SHOTS INT DEFAULT 0,
    SHOTS_ON_TARGET INT DEFAULT 0,
    POSSESSION INT DEFAULT 0,
    FOULS_COMMITTED INT DEFAULT 0,
    FOREIGN KEY (MATCH_ID) REFERENCES MATCHES(MATCH_ID) ON DELETE CASCADE,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID) ON DELETE CASCADE
);

CREATE TABLE TEAM_STATS (
    TEAM_ID BIGINT PRIMARY KEY,
    LEAGUE_ID BIGINT NOT NULL,
    MATCHES_PLAYED INT DEFAULT 0,
    WINS INT DEFAULT 0,
    DRAWS INT DEFAULT 0,
    LOSES INT DEFAULT 0,
    GOALS_SCORED INT DEFAULT 0,
    GOALS_CONCEDED INT DEFAULT 0,
    POINTS INT DEFAULT 0,
    GOAL_DIFFERENCE INT DEFAULT 0,
    FOREIGN KEY (TEAM_ID) REFERENCES TEAM(TEAM_ID) ON DELETE CASCADE,
    FOREIGN KEY (LEAGUE_ID) REFERENCES LEAGUE(LEAGUE_ID) ON DELETE CASCADE
);
