// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FootballService.proto
// Protobuf Java Version: 4.27.4

package com.behindthegoal.grpc;

public interface MatchStatsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.grpc.MatchStatsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 match_id = 1;</code>
   * @return The matchId.
   */
  long getMatchId();
}
