// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FootballService.proto
// Protobuf Java Version: 4.27.4

package com.behindthegoal.grpc;

/**
 * Protobuf type {@code api.grpc.MatchStats}
 */
public final class MatchStats extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:api.grpc.MatchStats)
    MatchStatsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 4,
      /* suffix= */ "",
      MatchStats.class.getName());
  }
  // Use MatchStats.newBuilder() to construct.
  private MatchStats(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MatchStats() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.behindthegoal.grpc.FootballServiceProto.internal_static_api_grpc_MatchStats_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.behindthegoal.grpc.FootballServiceProto.internal_static_api_grpc_MatchStats_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.behindthegoal.grpc.MatchStats.class, com.behindthegoal.grpc.MatchStats.Builder.class);
  }

  public static final int MATCH_ID_FIELD_NUMBER = 1;
  private long matchId_ = 0L;
  /**
   * <code>int64 match_id = 1;</code>
   * @return The matchId.
   */
  @java.lang.Override
  public long getMatchId() {
    return matchId_;
  }

  public static final int TEAM_ID_FIELD_NUMBER = 2;
  private long teamId_ = 0L;
  /**
   * <code>int64 team_id = 2;</code>
   * @return The teamId.
   */
  @java.lang.Override
  public long getTeamId() {
    return teamId_;
  }

  public static final int GOALS_FIELD_NUMBER = 3;
  private int goals_ = 0;
  /**
   * <code>int32 goals = 3;</code>
   * @return The goals.
   */
  @java.lang.Override
  public int getGoals() {
    return goals_;
  }

  public static final int YELLOW_CARDS_FIELD_NUMBER = 4;
  private int yellowCards_ = 0;
  /**
   * <code>int32 yellow_cards = 4;</code>
   * @return The yellowCards.
   */
  @java.lang.Override
  public int getYellowCards() {
    return yellowCards_;
  }

  public static final int RED_CARDS_FIELD_NUMBER = 5;
  private int redCards_ = 0;
  /**
   * <code>int32 red_cards = 5;</code>
   * @return The redCards.
   */
  @java.lang.Override
  public int getRedCards() {
    return redCards_;
  }

  public static final int SHOTS_FIELD_NUMBER = 6;
  private int shots_ = 0;
  /**
   * <code>int32 shots = 6;</code>
   * @return The shots.
   */
  @java.lang.Override
  public int getShots() {
    return shots_;
  }

  public static final int SHOTS_ON_TARGET_FIELD_NUMBER = 7;
  private int shotsOnTarget_ = 0;
  /**
   * <code>int32 shots_on_target = 7;</code>
   * @return The shotsOnTarget.
   */
  @java.lang.Override
  public int getShotsOnTarget() {
    return shotsOnTarget_;
  }

  public static final int POSSESSION_FIELD_NUMBER = 8;
  private int possession_ = 0;
  /**
   * <code>int32 possession = 8;</code>
   * @return The possession.
   */
  @java.lang.Override
  public int getPossession() {
    return possession_;
  }

  public static final int FOULS_COMMITTED_FIELD_NUMBER = 9;
  private int foulsCommitted_ = 0;
  /**
   * <code>int32 fouls_committed = 9;</code>
   * @return The foulsCommitted.
   */
  @java.lang.Override
  public int getFoulsCommitted() {
    return foulsCommitted_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (matchId_ != 0L) {
      output.writeInt64(1, matchId_);
    }
    if (teamId_ != 0L) {
      output.writeInt64(2, teamId_);
    }
    if (goals_ != 0) {
      output.writeInt32(3, goals_);
    }
    if (yellowCards_ != 0) {
      output.writeInt32(4, yellowCards_);
    }
    if (redCards_ != 0) {
      output.writeInt32(5, redCards_);
    }
    if (shots_ != 0) {
      output.writeInt32(6, shots_);
    }
    if (shotsOnTarget_ != 0) {
      output.writeInt32(7, shotsOnTarget_);
    }
    if (possession_ != 0) {
      output.writeInt32(8, possession_);
    }
    if (foulsCommitted_ != 0) {
      output.writeInt32(9, foulsCommitted_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (matchId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, matchId_);
    }
    if (teamId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, teamId_);
    }
    if (goals_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, goals_);
    }
    if (yellowCards_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, yellowCards_);
    }
    if (redCards_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, redCards_);
    }
    if (shots_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, shots_);
    }
    if (shotsOnTarget_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, shotsOnTarget_);
    }
    if (possession_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, possession_);
    }
    if (foulsCommitted_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, foulsCommitted_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.behindthegoal.grpc.MatchStats)) {
      return super.equals(obj);
    }
    com.behindthegoal.grpc.MatchStats other = (com.behindthegoal.grpc.MatchStats) obj;

    if (getMatchId()
        != other.getMatchId()) return false;
    if (getTeamId()
        != other.getTeamId()) return false;
    if (getGoals()
        != other.getGoals()) return false;
    if (getYellowCards()
        != other.getYellowCards()) return false;
    if (getRedCards()
        != other.getRedCards()) return false;
    if (getShots()
        != other.getShots()) return false;
    if (getShotsOnTarget()
        != other.getShotsOnTarget()) return false;
    if (getPossession()
        != other.getPossession()) return false;
    if (getFoulsCommitted()
        != other.getFoulsCommitted()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MATCH_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMatchId());
    hash = (37 * hash) + TEAM_ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTeamId());
    hash = (37 * hash) + GOALS_FIELD_NUMBER;
    hash = (53 * hash) + getGoals();
    hash = (37 * hash) + YELLOW_CARDS_FIELD_NUMBER;
    hash = (53 * hash) + getYellowCards();
    hash = (37 * hash) + RED_CARDS_FIELD_NUMBER;
    hash = (53 * hash) + getRedCards();
    hash = (37 * hash) + SHOTS_FIELD_NUMBER;
    hash = (53 * hash) + getShots();
    hash = (37 * hash) + SHOTS_ON_TARGET_FIELD_NUMBER;
    hash = (53 * hash) + getShotsOnTarget();
    hash = (37 * hash) + POSSESSION_FIELD_NUMBER;
    hash = (53 * hash) + getPossession();
    hash = (37 * hash) + FOULS_COMMITTED_FIELD_NUMBER;
    hash = (53 * hash) + getFoulsCommitted();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.behindthegoal.grpc.MatchStats parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.behindthegoal.grpc.MatchStats parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.behindthegoal.grpc.MatchStats parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.behindthegoal.grpc.MatchStats parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.behindthegoal.grpc.MatchStats parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.behindthegoal.grpc.MatchStats parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.behindthegoal.grpc.MatchStats parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.behindthegoal.grpc.MatchStats parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.behindthegoal.grpc.MatchStats parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.behindthegoal.grpc.MatchStats parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.behindthegoal.grpc.MatchStats parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.behindthegoal.grpc.MatchStats parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.behindthegoal.grpc.MatchStats prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.grpc.MatchStats}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.grpc.MatchStats)
      com.behindthegoal.grpc.MatchStatsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.behindthegoal.grpc.FootballServiceProto.internal_static_api_grpc_MatchStats_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.behindthegoal.grpc.FootballServiceProto.internal_static_api_grpc_MatchStats_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.behindthegoal.grpc.MatchStats.class, com.behindthegoal.grpc.MatchStats.Builder.class);
    }

    // Construct using com.behindthegoal.grpc.MatchStats.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      matchId_ = 0L;
      teamId_ = 0L;
      goals_ = 0;
      yellowCards_ = 0;
      redCards_ = 0;
      shots_ = 0;
      shotsOnTarget_ = 0;
      possession_ = 0;
      foulsCommitted_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.behindthegoal.grpc.FootballServiceProto.internal_static_api_grpc_MatchStats_descriptor;
    }

    @java.lang.Override
    public com.behindthegoal.grpc.MatchStats getDefaultInstanceForType() {
      return com.behindthegoal.grpc.MatchStats.getDefaultInstance();
    }

    @java.lang.Override
    public com.behindthegoal.grpc.MatchStats build() {
      com.behindthegoal.grpc.MatchStats result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.behindthegoal.grpc.MatchStats buildPartial() {
      com.behindthegoal.grpc.MatchStats result = new com.behindthegoal.grpc.MatchStats(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.behindthegoal.grpc.MatchStats result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.matchId_ = matchId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.teamId_ = teamId_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.goals_ = goals_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.yellowCards_ = yellowCards_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.redCards_ = redCards_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.shots_ = shots_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.shotsOnTarget_ = shotsOnTarget_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.possession_ = possession_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.foulsCommitted_ = foulsCommitted_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.behindthegoal.grpc.MatchStats) {
        return mergeFrom((com.behindthegoal.grpc.MatchStats)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.behindthegoal.grpc.MatchStats other) {
      if (other == com.behindthegoal.grpc.MatchStats.getDefaultInstance()) return this;
      if (other.getMatchId() != 0L) {
        setMatchId(other.getMatchId());
      }
      if (other.getTeamId() != 0L) {
        setTeamId(other.getTeamId());
      }
      if (other.getGoals() != 0) {
        setGoals(other.getGoals());
      }
      if (other.getYellowCards() != 0) {
        setYellowCards(other.getYellowCards());
      }
      if (other.getRedCards() != 0) {
        setRedCards(other.getRedCards());
      }
      if (other.getShots() != 0) {
        setShots(other.getShots());
      }
      if (other.getShotsOnTarget() != 0) {
        setShotsOnTarget(other.getShotsOnTarget());
      }
      if (other.getPossession() != 0) {
        setPossession(other.getPossession());
      }
      if (other.getFoulsCommitted() != 0) {
        setFoulsCommitted(other.getFoulsCommitted());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              matchId_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              teamId_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              goals_ = input.readInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              yellowCards_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              redCards_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              shots_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              shotsOnTarget_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              possession_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              foulsCommitted_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long matchId_ ;
    /**
     * <code>int64 match_id = 1;</code>
     * @return The matchId.
     */
    @java.lang.Override
    public long getMatchId() {
      return matchId_;
    }
    /**
     * <code>int64 match_id = 1;</code>
     * @param value The matchId to set.
     * @return This builder for chaining.
     */
    public Builder setMatchId(long value) {

      matchId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 match_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMatchId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      matchId_ = 0L;
      onChanged();
      return this;
    }

    private long teamId_ ;
    /**
     * <code>int64 team_id = 2;</code>
     * @return The teamId.
     */
    @java.lang.Override
    public long getTeamId() {
      return teamId_;
    }
    /**
     * <code>int64 team_id = 2;</code>
     * @param value The teamId to set.
     * @return This builder for chaining.
     */
    public Builder setTeamId(long value) {

      teamId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 team_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTeamId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      teamId_ = 0L;
      onChanged();
      return this;
    }

    private int goals_ ;
    /**
     * <code>int32 goals = 3;</code>
     * @return The goals.
     */
    @java.lang.Override
    public int getGoals() {
      return goals_;
    }
    /**
     * <code>int32 goals = 3;</code>
     * @param value The goals to set.
     * @return This builder for chaining.
     */
    public Builder setGoals(int value) {

      goals_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int32 goals = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearGoals() {
      bitField0_ = (bitField0_ & ~0x00000004);
      goals_ = 0;
      onChanged();
      return this;
    }

    private int yellowCards_ ;
    /**
     * <code>int32 yellow_cards = 4;</code>
     * @return The yellowCards.
     */
    @java.lang.Override
    public int getYellowCards() {
      return yellowCards_;
    }
    /**
     * <code>int32 yellow_cards = 4;</code>
     * @param value The yellowCards to set.
     * @return This builder for chaining.
     */
    public Builder setYellowCards(int value) {

      yellowCards_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 yellow_cards = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearYellowCards() {
      bitField0_ = (bitField0_ & ~0x00000008);
      yellowCards_ = 0;
      onChanged();
      return this;
    }

    private int redCards_ ;
    /**
     * <code>int32 red_cards = 5;</code>
     * @return The redCards.
     */
    @java.lang.Override
    public int getRedCards() {
      return redCards_;
    }
    /**
     * <code>int32 red_cards = 5;</code>
     * @param value The redCards to set.
     * @return This builder for chaining.
     */
    public Builder setRedCards(int value) {

      redCards_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 red_cards = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRedCards() {
      bitField0_ = (bitField0_ & ~0x00000010);
      redCards_ = 0;
      onChanged();
      return this;
    }

    private int shots_ ;
    /**
     * <code>int32 shots = 6;</code>
     * @return The shots.
     */
    @java.lang.Override
    public int getShots() {
      return shots_;
    }
    /**
     * <code>int32 shots = 6;</code>
     * @param value The shots to set.
     * @return This builder for chaining.
     */
    public Builder setShots(int value) {

      shots_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 shots = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearShots() {
      bitField0_ = (bitField0_ & ~0x00000020);
      shots_ = 0;
      onChanged();
      return this;
    }

    private int shotsOnTarget_ ;
    /**
     * <code>int32 shots_on_target = 7;</code>
     * @return The shotsOnTarget.
     */
    @java.lang.Override
    public int getShotsOnTarget() {
      return shotsOnTarget_;
    }
    /**
     * <code>int32 shots_on_target = 7;</code>
     * @param value The shotsOnTarget to set.
     * @return This builder for chaining.
     */
    public Builder setShotsOnTarget(int value) {

      shotsOnTarget_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int32 shots_on_target = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearShotsOnTarget() {
      bitField0_ = (bitField0_ & ~0x00000040);
      shotsOnTarget_ = 0;
      onChanged();
      return this;
    }

    private int possession_ ;
    /**
     * <code>int32 possession = 8;</code>
     * @return The possession.
     */
    @java.lang.Override
    public int getPossession() {
      return possession_;
    }
    /**
     * <code>int32 possession = 8;</code>
     * @param value The possession to set.
     * @return This builder for chaining.
     */
    public Builder setPossession(int value) {

      possession_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int32 possession = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPossession() {
      bitField0_ = (bitField0_ & ~0x00000080);
      possession_ = 0;
      onChanged();
      return this;
    }

    private int foulsCommitted_ ;
    /**
     * <code>int32 fouls_committed = 9;</code>
     * @return The foulsCommitted.
     */
    @java.lang.Override
    public int getFoulsCommitted() {
      return foulsCommitted_;
    }
    /**
     * <code>int32 fouls_committed = 9;</code>
     * @param value The foulsCommitted to set.
     * @return This builder for chaining.
     */
    public Builder setFoulsCommitted(int value) {

      foulsCommitted_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int32 fouls_committed = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearFoulsCommitted() {
      bitField0_ = (bitField0_ & ~0x00000100);
      foulsCommitted_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:api.grpc.MatchStats)
  }

  // @@protoc_insertion_point(class_scope:api.grpc.MatchStats)
  private static final com.behindthegoal.grpc.MatchStats DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.behindthegoal.grpc.MatchStats();
  }

  public static com.behindthegoal.grpc.MatchStats getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MatchStats>
      PARSER = new com.google.protobuf.AbstractParser<MatchStats>() {
    @java.lang.Override
    public MatchStats parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MatchStats> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MatchStats> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.behindthegoal.grpc.MatchStats getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

