// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FootballService.proto
// Protobuf Java Version: 4.27.4

package com.behindthegoal.grpc;

public interface MatchStatsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.grpc.MatchStatsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.grpc.MatchStats match_stats = 1;</code>
   */
  java.util.List<com.behindthegoal.grpc.MatchStats> 
      getMatchStatsList();
  /**
   * <code>repeated .api.grpc.MatchStats match_stats = 1;</code>
   */
  com.behindthegoal.grpc.MatchStats getMatchStats(int index);
  /**
   * <code>repeated .api.grpc.MatchStats match_stats = 1;</code>
   */
  int getMatchStatsCount();
  /**
   * <code>repeated .api.grpc.MatchStats match_stats = 1;</code>
   */
  java.util.List<? extends com.behindthegoal.grpc.MatchStatsOrBuilder> 
      getMatchStatsOrBuilderList();
  /**
   * <code>repeated .api.grpc.MatchStats match_stats = 1;</code>
   */
  com.behindthegoal.grpc.MatchStatsOrBuilder getMatchStatsOrBuilder(
      int index);
}
