// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: FootballService.proto
// Protobuf Java Version: 4.27.4

package com.behindthegoal.grpc;

/**
 * Protobuf type {@code api.grpc.TeamListResponse}
 */
public final class TeamListResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:api.grpc.TeamListResponse)
    TeamListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 4,
      /* suffix= */ "",
      TeamListResponse.class.getName());
  }
  // Use TeamListResponse.newBuilder() to construct.
  private TeamListResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TeamListResponse() {
    teams_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.behindthegoal.grpc.FootballServiceProto.internal_static_api_grpc_TeamListResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.behindthegoal.grpc.FootballServiceProto.internal_static_api_grpc_TeamListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.behindthegoal.grpc.TeamListResponse.class, com.behindthegoal.grpc.TeamListResponse.Builder.class);
  }

  public static final int TEAMS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.behindthegoal.grpc.Team> teams_;
  /**
   * <code>repeated .api.grpc.Team teams = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.behindthegoal.grpc.Team> getTeamsList() {
    return teams_;
  }
  /**
   * <code>repeated .api.grpc.Team teams = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.behindthegoal.grpc.TeamOrBuilder> 
      getTeamsOrBuilderList() {
    return teams_;
  }
  /**
   * <code>repeated .api.grpc.Team teams = 1;</code>
   */
  @java.lang.Override
  public int getTeamsCount() {
    return teams_.size();
  }
  /**
   * <code>repeated .api.grpc.Team teams = 1;</code>
   */
  @java.lang.Override
  public com.behindthegoal.grpc.Team getTeams(int index) {
    return teams_.get(index);
  }
  /**
   * <code>repeated .api.grpc.Team teams = 1;</code>
   */
  @java.lang.Override
  public com.behindthegoal.grpc.TeamOrBuilder getTeamsOrBuilder(
      int index) {
    return teams_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < teams_.size(); i++) {
      output.writeMessage(1, teams_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < teams_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, teams_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.behindthegoal.grpc.TeamListResponse)) {
      return super.equals(obj);
    }
    com.behindthegoal.grpc.TeamListResponse other = (com.behindthegoal.grpc.TeamListResponse) obj;

    if (!getTeamsList()
        .equals(other.getTeamsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTeamsCount() > 0) {
      hash = (37 * hash) + TEAMS_FIELD_NUMBER;
      hash = (53 * hash) + getTeamsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.behindthegoal.grpc.TeamListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.behindthegoal.grpc.TeamListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.behindthegoal.grpc.TeamListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.behindthegoal.grpc.TeamListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.behindthegoal.grpc.TeamListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.behindthegoal.grpc.TeamListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.behindthegoal.grpc.TeamListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.behindthegoal.grpc.TeamListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.behindthegoal.grpc.TeamListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.behindthegoal.grpc.TeamListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.behindthegoal.grpc.TeamListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.behindthegoal.grpc.TeamListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.behindthegoal.grpc.TeamListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.grpc.TeamListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.grpc.TeamListResponse)
      com.behindthegoal.grpc.TeamListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.behindthegoal.grpc.FootballServiceProto.internal_static_api_grpc_TeamListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.behindthegoal.grpc.FootballServiceProto.internal_static_api_grpc_TeamListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.behindthegoal.grpc.TeamListResponse.class, com.behindthegoal.grpc.TeamListResponse.Builder.class);
    }

    // Construct using com.behindthegoal.grpc.TeamListResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (teamsBuilder_ == null) {
        teams_ = java.util.Collections.emptyList();
      } else {
        teams_ = null;
        teamsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.behindthegoal.grpc.FootballServiceProto.internal_static_api_grpc_TeamListResponse_descriptor;
    }

    @java.lang.Override
    public com.behindthegoal.grpc.TeamListResponse getDefaultInstanceForType() {
      return com.behindthegoal.grpc.TeamListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.behindthegoal.grpc.TeamListResponse build() {
      com.behindthegoal.grpc.TeamListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.behindthegoal.grpc.TeamListResponse buildPartial() {
      com.behindthegoal.grpc.TeamListResponse result = new com.behindthegoal.grpc.TeamListResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.behindthegoal.grpc.TeamListResponse result) {
      if (teamsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          teams_ = java.util.Collections.unmodifiableList(teams_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.teams_ = teams_;
      } else {
        result.teams_ = teamsBuilder_.build();
      }
    }

    private void buildPartial0(com.behindthegoal.grpc.TeamListResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.behindthegoal.grpc.TeamListResponse) {
        return mergeFrom((com.behindthegoal.grpc.TeamListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.behindthegoal.grpc.TeamListResponse other) {
      if (other == com.behindthegoal.grpc.TeamListResponse.getDefaultInstance()) return this;
      if (teamsBuilder_ == null) {
        if (!other.teams_.isEmpty()) {
          if (teams_.isEmpty()) {
            teams_ = other.teams_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTeamsIsMutable();
            teams_.addAll(other.teams_);
          }
          onChanged();
        }
      } else {
        if (!other.teams_.isEmpty()) {
          if (teamsBuilder_.isEmpty()) {
            teamsBuilder_.dispose();
            teamsBuilder_ = null;
            teams_ = other.teams_;
            bitField0_ = (bitField0_ & ~0x00000001);
            teamsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getTeamsFieldBuilder() : null;
          } else {
            teamsBuilder_.addAllMessages(other.teams_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.behindthegoal.grpc.Team m =
                  input.readMessage(
                      com.behindthegoal.grpc.Team.parser(),
                      extensionRegistry);
              if (teamsBuilder_ == null) {
                ensureTeamsIsMutable();
                teams_.add(m);
              } else {
                teamsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.behindthegoal.grpc.Team> teams_ =
      java.util.Collections.emptyList();
    private void ensureTeamsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        teams_ = new java.util.ArrayList<com.behindthegoal.grpc.Team>(teams_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.behindthegoal.grpc.Team, com.behindthegoal.grpc.Team.Builder, com.behindthegoal.grpc.TeamOrBuilder> teamsBuilder_;

    /**
     * <code>repeated .api.grpc.Team teams = 1;</code>
     */
    public java.util.List<com.behindthegoal.grpc.Team> getTeamsList() {
      if (teamsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(teams_);
      } else {
        return teamsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .api.grpc.Team teams = 1;</code>
     */
    public int getTeamsCount() {
      if (teamsBuilder_ == null) {
        return teams_.size();
      } else {
        return teamsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .api.grpc.Team teams = 1;</code>
     */
    public com.behindthegoal.grpc.Team getTeams(int index) {
      if (teamsBuilder_ == null) {
        return teams_.get(index);
      } else {
        return teamsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .api.grpc.Team teams = 1;</code>
     */
    public Builder setTeams(
        int index, com.behindthegoal.grpc.Team value) {
      if (teamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTeamsIsMutable();
        teams_.set(index, value);
        onChanged();
      } else {
        teamsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api.grpc.Team teams = 1;</code>
     */
    public Builder setTeams(
        int index, com.behindthegoal.grpc.Team.Builder builderForValue) {
      if (teamsBuilder_ == null) {
        ensureTeamsIsMutable();
        teams_.set(index, builderForValue.build());
        onChanged();
      } else {
        teamsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.grpc.Team teams = 1;</code>
     */
    public Builder addTeams(com.behindthegoal.grpc.Team value) {
      if (teamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTeamsIsMutable();
        teams_.add(value);
        onChanged();
      } else {
        teamsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .api.grpc.Team teams = 1;</code>
     */
    public Builder addTeams(
        int index, com.behindthegoal.grpc.Team value) {
      if (teamsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTeamsIsMutable();
        teams_.add(index, value);
        onChanged();
      } else {
        teamsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api.grpc.Team teams = 1;</code>
     */
    public Builder addTeams(
        com.behindthegoal.grpc.Team.Builder builderForValue) {
      if (teamsBuilder_ == null) {
        ensureTeamsIsMutable();
        teams_.add(builderForValue.build());
        onChanged();
      } else {
        teamsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.grpc.Team teams = 1;</code>
     */
    public Builder addTeams(
        int index, com.behindthegoal.grpc.Team.Builder builderForValue) {
      if (teamsBuilder_ == null) {
        ensureTeamsIsMutable();
        teams_.add(index, builderForValue.build());
        onChanged();
      } else {
        teamsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.grpc.Team teams = 1;</code>
     */
    public Builder addAllTeams(
        java.lang.Iterable<? extends com.behindthegoal.grpc.Team> values) {
      if (teamsBuilder_ == null) {
        ensureTeamsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, teams_);
        onChanged();
      } else {
        teamsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .api.grpc.Team teams = 1;</code>
     */
    public Builder clearTeams() {
      if (teamsBuilder_ == null) {
        teams_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        teamsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .api.grpc.Team teams = 1;</code>
     */
    public Builder removeTeams(int index) {
      if (teamsBuilder_ == null) {
        ensureTeamsIsMutable();
        teams_.remove(index);
        onChanged();
      } else {
        teamsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .api.grpc.Team teams = 1;</code>
     */
    public com.behindthegoal.grpc.Team.Builder getTeamsBuilder(
        int index) {
      return getTeamsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .api.grpc.Team teams = 1;</code>
     */
    public com.behindthegoal.grpc.TeamOrBuilder getTeamsOrBuilder(
        int index) {
      if (teamsBuilder_ == null) {
        return teams_.get(index);  } else {
        return teamsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .api.grpc.Team teams = 1;</code>
     */
    public java.util.List<? extends com.behindthegoal.grpc.TeamOrBuilder> 
         getTeamsOrBuilderList() {
      if (teamsBuilder_ != null) {
        return teamsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(teams_);
      }
    }
    /**
     * <code>repeated .api.grpc.Team teams = 1;</code>
     */
    public com.behindthegoal.grpc.Team.Builder addTeamsBuilder() {
      return getTeamsFieldBuilder().addBuilder(
          com.behindthegoal.grpc.Team.getDefaultInstance());
    }
    /**
     * <code>repeated .api.grpc.Team teams = 1;</code>
     */
    public com.behindthegoal.grpc.Team.Builder addTeamsBuilder(
        int index) {
      return getTeamsFieldBuilder().addBuilder(
          index, com.behindthegoal.grpc.Team.getDefaultInstance());
    }
    /**
     * <code>repeated .api.grpc.Team teams = 1;</code>
     */
    public java.util.List<com.behindthegoal.grpc.Team.Builder> 
         getTeamsBuilderList() {
      return getTeamsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.behindthegoal.grpc.Team, com.behindthegoal.grpc.Team.Builder, com.behindthegoal.grpc.TeamOrBuilder> 
        getTeamsFieldBuilder() {
      if (teamsBuilder_ == null) {
        teamsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.behindthegoal.grpc.Team, com.behindthegoal.grpc.Team.Builder, com.behindthegoal.grpc.TeamOrBuilder>(
                teams_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        teams_ = null;
      }
      return teamsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:api.grpc.TeamListResponse)
  }

  // @@protoc_insertion_point(class_scope:api.grpc.TeamListResponse)
  private static final com.behindthegoal.grpc.TeamListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.behindthegoal.grpc.TeamListResponse();
  }

  public static com.behindthegoal.grpc.TeamListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TeamListResponse>
      PARSER = new com.google.protobuf.AbstractParser<TeamListResponse>() {
    @java.lang.Override
    public TeamListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TeamListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TeamListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.behindthegoal.grpc.TeamListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

